{{- if .Values.enableWorkloadScalingApp }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-scaling-operators
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  source:
    path: openshift/openshift-gitops/helm/workload-scaling/
    repoURL: https://github.com/scotttyso/Cisco-AI-Pods/tree/main.git
    targetRevision: main
    helm:
      valuesObject:
        {{- .Values.configuration.WorkloadScalingApp | toYaml | nindent 8 }}
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false 
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
{{- end }}