apiVersion: sriovnetwork.openshift.io/v1
kind: SriovOperatorConfig
metadata:
  name: default
  namespace: openshift-sriov-network-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "13"
spec:
  enableInjector: true
  enableOperatorWebhook: true
  logLevel: 2
  configDaemonNodeSelector:
    network.nvidia.com/operator.mofed.wait: "false"
    node-role.kubernetes.io/worker: ""
    feature.node.kubernetes.io/pci-15b3.sriov.capable: "true"