apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
  namespace: nvidia-gpu-operator
  annotations:
    argocd.argoproj.io/sync-wave: "25"
data:
  dcgm-metrics.csv: |-
    {{ .Files.Get "files/dcgm-metrics.csv" | nindent 4 }}