apiVersion: v1
kind: Namespace
metadata:
  name: openshift-opentelemetry-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/display-name: "Red Hat OpenShift distributed tracing data collection"
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: opentelemetry-operator
  namespace: openshift-opentelemetry-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-product
  namespace: openshift-opentelemetry-operator
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  channel: stable
  name: opentelemetry-product
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: {{ .Values.installPlanApproval | default "Manual" }}