apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-feature-discovery
  namespace: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable
  installPlanApproval: Automatic
  name: node-feature-discovery
  source: redhat-operators
  sourceNamespace: openshift-marketplace