---
  - name: Slack Notifications | Obtain Slack Token | for {{ array_fqdn }}
    set_fact:
      slack_token: "{{ lookup('ansible.builtin.env', 'slack_token') }}"

  - name: Slack Notifications | Network | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_slack_network.yaml"
    when: pure_storage.settings.network is defined

  - name: Slack Notifications | Security | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_slack_security.yaml"
    when: pure_storage.settings.security is defined

  - name: Slack Notifications | System | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_slack_system.yaml"
    when: pure_storage.settings.system is defined
