---
  - name: Notifications | Check if Slack is defined | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_slack.yaml"
    when: pure_storage.notifications.slack is defined

  - name: Notifications | Check if Microsoft Teams is defined | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_microsoft_teams.yaml"
    when: pure_storage.notifications.microsoft_teams is defined

  - name: Notifications | Check if Cisco WebEx is defined | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_cisco_webex.yaml"
    when: pure_storage.notifications.cisco_webex is defined

