---
  - name: Microsoft Team Notifications | Obtain Microsoft Teams WebHook | for {{ array_fqdn }}
    set_fact:
      microsoft_teams_webhook: "{{ lookup('ansible.builtin.env', 'microsoft_teams_webhook') }}"

  - name: Microsoft Team Notifications | Network | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_microsoft_teams_network.yaml"
    when: pure_storage.settings.network is defined

  - name: Microsoft Team Notifications | Security | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_microsoft_teams_security.yaml"
    when: pure_storage.settings.security is defined

  - name: Microsoft Team Notifications | System | for {{ array_fqdn }}
    include_tasks:
      file: "{{ playbook_dir }}/tasks/flash_blade/notifications_microsoft_teams_system.yaml"
    when: pure_storage.settings.system is defined
