---
############################
# Alerts and Notifications
############################

- name: Microsoft Team Notifications | Change for System > Alert Routing on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} alert routing configuration has changed\n{{ alert_routing_change | to_nice_yaml }}"
  when: alert_routing_change.changed

- name: Microsoft Team Notifications | Change for System > Alert Watchers on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} alert watchers configuration has changed\n{{ alert_watchers_change.results | map(attribute='invocation') | map(attribute='module_args') | to_nice_yaml }}"
  when: alert_watchers_change.changed

############################
# Array Details
############################

- name: Microsoft Team Notifications | Change for System > Array Name on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} hostname configuration has changed\n{{ array_name_change | to_nice_yaml }}"
  when: array_name_change.changed

- name: Microsoft Team Notifications | Change for System > Idle Timeout on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} idle timeout configuration has changed\n{{ idle_timeout_change | to_nice_yaml }}"
  when: idle_timeout_change.changed

- name: Microsoft Team Notifications | Change for System > Login Banner on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} login banner configuration has changed\n{{ login_banner_change | to_nice_yaml }}"
  when: login_banner_change.changed

- name: Microsoft Team Notifications | Change for System > Timezone on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} timezone configuration has changed\n{{ timezone_change | to_nice_yaml }}"
  when: timezone_change.changed

############################
# NTP Servers
############################

- name: Microsoft Team Notifications | Change for System > NTP Servers on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} NTP servers configuration has changed\n{{ ntp_servers_change | to_nice_yaml }}"
  when: ntp_servers_change.changed

############################
# Monitoring
############################

- name: Microsoft Team Notifications | Change for System > Syslog Server Connections on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} syslog server connections configuration has changed\n{{ syslog_server_connections_change.results | map(attribute='invocation') | map(attribute='module_args') | to_nice_yaml }}"
  when: syslog_server_connections_change.changed

- name: Microsoft Team Notifications | Change for System > SNMP Manager v2c on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} SNMP manager v2c configuration has changed\n{{ snmp_manager_v2c_change.results | map(attribute='invocation') | map(attribute='module_args') | to_nice_yaml }}"
  when: snmp_manager_v2c_change.changed

- name: Microsoft Team Notifications | Change for System > SNMP Manager v3 on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} SNMP manager v3 configuration has changed\n{{ snmp_manager_v3_change.results | map(attribute='invocation') | map(attribute='module_args') | to_nice_yaml }}"
  when: snmp_manager_v3_change.changed

- name: Microsoft Team Notifications | Change for System > Phone Home on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} phone home configuration has changed\n{{ phone_home_change | to_nice_yaml }}"
  when: phone_home_change.changed

- name: Microsoft Team Notifications | Change for System > Proxy Server on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} proxy server configuration has changed\n{{ proxy_server_change | to_nice_yaml }}"
  when: proxy_server_change.changed

- name: Microsoft Team Notifications | Change for System > Remote Assist on {{ array_fqdn }} # noqa: no-handler
  community.general.office_365_connector_card:
    webhook: "{{ microsoft_teams_webhook }}"
    text: "{{ msg.split('\n') }}"
  vars:
    msg: "Array {{ array_fqdn }} remote assist configuration has changed\n{{ remote_assist_change | to_nice_yaml }}"
  when: remote_assist_change.changed
