---
- name: Build IP pools consumed from Policies
  ansible.builtin.set_fact:
    consumed_ip_pools: >
      {%- set pools = [] -%}
      {%- set subelems = query('ansible.builtin.subelements', merged_model.intersight.organizations | dict2items, 'value.policies.imc_access', {'skip_missing': True}) -%}
      {%- for org_item, imc_policy in subelems -%}
        {%- if imc_policy.inband_ip_pool is defined -%}
          {%- set _ = pools.append({
            'name': imc_policy.inband_ip_pool.rsplit('/', 1) | last,
            'organization': imc_policy.inband_ip_pool.rsplit('/', 1) | first if '/' in imc_policy.inband_ip_pool else org_item.key
          }) -%}
        {%- endif -%}
        {%- if imc_policy.out_of_band_ip_pool is defined -%}
          {%- set _ = pools.append({
            'name': imc_policy.out_of_band_ip_pool.rsplit('/', 1) | last,
            'organization': imc_policy.out_of_band_ip_pool.rsplit('/', 1) | first if '/' in imc_policy.out_of_band_ip_pool else org_item.key
          }) -%}
        {%- endif -%}
      {%- endfor -%}
      {%- set iscsi_subelems = query('ansible.builtin.subelements', merged_model.intersight.organizations | dict2items, 'value.policies.iscsi_boot', {'skip_missing': True}) -%}
      {%- for org_item, iscsi_policy in iscsi_subelems -%}
        {%- if iscsi_policy.initiator_ip_pool is defined -%}
          {%- set _ = pools.append({
            'name': iscsi_policy.initiator_ip_pool.rsplit('/', 1) | last,
            'organization': iscsi_policy.initiator_ip_pool.rsplit('/', 1) | first if '/' in iscsi_policy.initiator_ip_pool else org_item.key
          }) -%}
        {%- endif -%}
      {%- endfor -%}
      {{ pools }}

- name: Get IP Pools from Intersight
  # noqa: args[module]
  cisco.intersight.intersight_ip_pool_info:
    name: "{{ item.name }}"
    organization: "{{ item.organization }}"
    validate_certs: "{{ module_validate_certs }}"
  loop: "{{ consumed_ip_pools | default([]) | map('to_json') | unique | map('from_json') | list }}"
  loop_control:
    label: "{{ (item.organization | default('global')) ~ '/' ~ (item.name | default(item.key | default(item | string))) }}"
  register: ip_pools_info

- name: Set ip pools dictionary
  ansible.builtin.set_fact:
    ip_pools_by_org: >-
      {{
        ip_pools_by_org | default({})
        | combine({
            organization_name: (
              ip_pools_by_org[organization_name] | default({})
            ) | combine({ item.Name: pool_details })
          }, recursive=True)
      }}
  vars:
    organization_name: "{{ org_moid_to_name[item.Organization.Moid] }}"
    pool_details:
      moid: "{{ item.Moid }}"
      ipv4_blocks: "{{ item.IpV4Blocks }}"
      ipv6_blocks: "{{ item.IpV6Blocks }}"
  loop: >
    {{ ip_pools_info.results | map(attribute='api_response') | flatten | list }}

- name: Debug IP Pools dictionary
  ansible.builtin.debug:
    var: ip_pools_by_org
  when: debug_module | bool
