apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-file-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi 
  storageClassName: px-gold-file
