---
intersight_root_dir: "{{ (playbook_dir ~ '/..') | realpath }}"
intersight_model_root: "{{ intersight_root_dir }}"
intersight_api_key_id: "{{ lookup('ansible.builtin.env', 'intersight_api_key_id') }}"
intersight_api_private_key: "{{ lookup('ansible.builtin.env', 'intersight_secret_key') }}"
intersight_api_uri: "{{ lookup('ansible.builtin.env', 'intersight_api_uri') | default('https://intersight.com/api/v1', true) }}"
intersight_validate_certs: "{{ lookup('ansible.builtin.env', 'intersight_validate_certs') | default('true', true) | bool }}"
intersight_schema: "{{ lookup('ansible.builtin.file', intersight_root_dir ~ '/../schema/cisco-ai-pods.json') | from_json }}"
