---
############################
# Certificates
############################

- name: Cisco WebEx Notifications | Change for System > Certificates on {{ array_fqdn }} # noqa: no-handler
  community.general.cisco_webex:
    msg: "{{ msg.split('\n') }}"
    msg_type: text
    personal_token: "{{ cisco_webex_token }}"
    recipient_id: "{{ recipient_id }}"
    recipient_type: "{{ recipient_type }}"
  vars:
    msg: "Array {{ array_fqdn }} has changed configuration\n{{ certificates_change.results[0].invocation.module_args | to_nice_yaml }}"
  when: certificates_change.changed

- name: Cisco WebEx Notifications | Change for System > Certificate Groups on {{ array_fqdn }} # noqa: no-handler
  community.general.cisco_webex:
    msg: "{{ msg.split('\n') }}"
    msg_type: text
    personal_token: "{{ cisco_webex_token }}"
    recipient_id: "{{ recipient_id }}"
    recipient_type: "{{ recipient_type }}"
  vars:
    msg: "Array {{ array_fqdn }} has changed configuration\n{{ certificate_groups_change.results[0].invocation.module_args | to_nice_yaml }}"
  when: certificate_groups_change.changed

############################
# Directory Service
############################

- name: Cisco WebEx Notifications | Change for System > Directory Service on {{ array_fqdn }} # noqa: no-handler
  community.general.cisco_webex:
    msg: "{{ msg.split('\n') }}"
    msg_type: text
    personal_token: "{{ cisco_webex_token }}"
    recipient_id: "{{ recipient_id }}"
    recipient_type: "{{ recipient_type }}"
  vars:
    msg: "Array {{ array_fqdn }} has changed configuration\n{{ directory_service_change.results[0].invocation.module_args | to_nice_yaml }}"
  when: directory_service_change.changed

- name: Cisco WebEx Notifications | Change for System > Directory Service Role Mappings on {{ array_fqdn }} # noqa: no-handler
  community.general.cisco_webex:
    msg: "{{ msg.split('\n') }}"
    msg_type: text
    personal_token: "{{ cisco_webex_token }}"
    recipient_id: "{{ recipient_id }}"
    recipient_type: "{{ recipient_type }}"
  vars:
    msg: "Array {{ array_fqdn }} has changed configuration\n{{ directory_service_role_mappings_change.results[0].invocation.module_args | to_nice_yaml }}"
  when: directory_service_role_mappings_change.changed
