apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/scotttyso/Cisco-AI-Pods/tree/main.git
    path: openshift/openshift-gitops/rhoai_install/app_of_apps/
    targetRevision: main
    helm:
      valuesObject:
        installPlanApproval: Manual
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated: {}
    syncOptions:
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true