---
- name: Add API Certificate to OpenShift cluster
  connection: local
  hosts: localhost
  gather_facts: no
  vars:
    validate_certificates: false

  tasks:
    #####################
    # API CERTIFICATE
    #####################
    - name: Read API Certificate Chain File Content
      ansible.builtin.slurp:
        src: "{{ lookup('ansible.builtin.env', 'api_cert_chain_file') }}"
      register: api_cert_chain_file

    - name: Parse the API Certificate Chain File as PEM
      ansible.builtin.set_fact:
        is_pem_cert: "{{ api_cert_chain_file['content'] | b64decode | community.crypto.x509_certificate_info is success }}"
      register: api_cert_chain_cert_info
      ignore_errors: true # Ignore errors if parsing fails

    - name: Report API Certificate Chain File Type
      ansible.builtin.debug:
        msg: "API Certificate Chain File is a valid PEM certificate."
      when: not api_cert_chain_cert_info.failed
      failed_when: api_cert_chain_cert_info.failed

    - name: Read API Key File Content
      ansible.builtin.slurp:
        src: "{{ lookup('ansible.builtin.env', 'api_key_file') }}"
      register: api_key_file

    - name: Parse the API Key File as PEM
      ansible.builtin.set_fact:
        is_pem_cert: "{{ api_key_file['content'] | b64decode | community.crypto.openssl_privatekey_info is success }}"
      register: api_key_info
      ignore_errors: true # Ignore errors if parsing fails

    - name: Report API Key File Type
      ansible.builtin.debug:
        msg: "API Key File is a valid PEM Key File."
      when: not api_key_info.failed
      failed_when: api_key_info.failed

    - name: Encode PEM Files
      ansible.builtin.set_fact:
        api_cert_chain_file_b64: "{{ lookup('file', lookup('ansible.builtin.env', 'api_cert_chain_file')) | b64encode }}"
        api_key_file_b64: "{{ lookup('file', lookup('ansible.builtin.env', 'api_key_file')) | b64encode }}"

    - name: Log in to OpenShift (requires oc binary on host)
      ansible.builtin.command:
        cmd: oc login --token={{ lookup('ansible.builtin.env', 'openshift_token_id') }} --server={{ lookup('ansible.builtin.env', 'openshift_api_url') }}
      register: login_result
      no_log: true # Prevent sensitive info in logs
    
    - name: Create API TLS Secret
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', 'api-tls-secret.yaml.j2') | from_yaml }}"
        validate_certs: "{{ validate_certificates }}"

    - name: Patch API to use new TLS Secrets
      ansible.builtin.shell: |
        oc patch apiserver cluster --type=merge -p '{"spec":{"servingCerts": {"namedCertificates": [{"names": ["{{ lookup('ansible.builtin.env', 'api_server_hostname') }}"], "servingCertificate": {"name": "api-tls-secret"}}]}}}'

    - name: Pause for 2 minutes to allow API to restart with new certificate
      ansible.builtin.pause:
        minutes: 2

    - name: Wait for Kube API Server to be Ready after Certificate Update
      kubernetes.core.k8s_info:
        api_version: operator.openshift.io/v1
        kind: KubeAPIServer
        name: cluster
        validate_certs: "{{ validate_certificates }}"
      register: kube_apiserver
      until:
        - kube_apiserver.resources is defined
        - kube_apiserver.resources[0].status.conditions | selectattr('type', 'equalto', 'NodeInstallerProgressing') | map(attribute='status') | first == 'False'
      retries: 30
      delay: 60

    # - name: Log out of OpenShift
    #   ansible.builtin.command:
    #     cmd: oc logout
    #   register: logout_result
    #   no_log: true # Prevent sensitive info in logs
