---
- name: Add API Certificate to OpenShift cluster
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    validate_certificates: false
    openshift_api_url: "{{ lookup('ansible.builtin.env', 'openshift_api_url') }}"
    openshift_token: "{{ lookup('ansible.builtin.env', 'openshift_token_id') }}"

  module_defaults:
    group/kubernetes.core.all:
      host: "{{ openshift_api_url }}"
      api_key: "{{ openshift_token }}"
      validate_certs: "{{ validate_certificates }}"

  pre_tasks:
    - name: Verify required environment variables are set
      ansible.builtin.assert:
        that:
          - openshift_token | length > 0
          - openshift_api_url | length > 0
        fail_msg: "Required environment variables not set: openshift_token_id, openshift_api_url"

  tasks:

    - name: Wait for Kube API Server to be Ready after Certificate Update
      kubernetes.core.k8s_info:
        api_version: operator.openshift.io/v1
        kind: KubeAPIServer
        name: cluster
        validate_certs: "{{ validate_certificates }}"
      register: kube_apiserver
      until:
        - kube_apiserver.resources is defined
        - kube_apiserver.resources[0].status.conditions | selectattr('type', 'equalto', 'NodeInstallerProgressing') | map(attribute='status') | first == 'False'
      retries: 30
      delay: 60
