---
- name: Add Ingress Certificate to OpenShift cluster
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    validate_certificates: false
    openshift_api_url: "{{ lookup('ansible.builtin.env', 'openshift_api_url') }}"
    openshift_token: "{{ lookup('ansible.builtin.env', 'openshift_token_id') }}"

  module_defaults:
    group/kubernetes.core.all:
      host: "{{ openshift_api_url }}"
      api_key: "{{ openshift_token }}"
      validate_certs: "{{ validate_certificates }}"

  pre_tasks:
    - name: Verify required environment variables are set
      ansible.builtin.assert:
        that:
          - openshift_token | length > 0
          - openshift_api_url | length > 0
        fail_msg: "Required environment variables not set: openshift_token_id, openshift_api_url"

  tasks:

    - name: Verify Ingress Controller Patch
      kubernetes.core.k8s_info:
        api_version: operator.openshift.io/v1
        kind: IngressController
        name: default
        namespace: openshift-ingress-operator
        validate_certs: "{{ validate_certificates }}"
      register: ingress_controller_patch_result

    - name: Report Ingress Controller Patch Result
      ansible.builtin.debug:
        msg: "Ingress Controller default certificate is set to ingress-tls-secret"
      failed_when: ingress_controller_patch_result.resources[0].spec.defaultCertificate.name | default('') != 'ingress-tls-secret'

    - name: Wait for OpenShift OAuth Pods to be Ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: openshift-authentication
        field_selectors:
          - status.phase=Running
      register: oauth_pods
      until:
        - oauth_pods.resources | length > 0
        - oauth_pods.resources | map(attribute='status.containerStatuses') | flatten | map(attribute='ready') | reject('equalto', true) | list | length == 0
      retries: 30
      delay: 10

    - name: Wait for Ingress Router Pods to be Ready
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: openshift-ingress
        field_selectors:
          - status.phase=Running
      register: ingress_pods
      until:
        - ingress_pods.resources | length > 0
        - ingress_pods.resources | map(attribute='status.containerStatuses') | flatten | map(attribute='ready') | reject('equalto', true) | list | length == 0
      retries: 30
      delay: 10
