---
openshift_api_url: "{{ lookup('ansible.builtin.env', 'openshift_api_url') }}"
openshift_token: "{{ lookup('ansible.builtin.env', 'openshift_token_id') }}"
portworx_version: ""
portworx_namespace: "portworx"
prompt_before_storagecluster_apply: false
