---
openshift_api_url: "{{ lookup('ansible.builtin.env', 'openshift_api_url') }}"
openshift_token: "{{ lookup('ansible.builtin.env', 'openshift_token_id') }}"
openshift_validate_certs: true
certificate_wait_minutes: 2
certificate_prompt_before_apply: false
