---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    name: nvidia-network-operator
    openshift.io/cluster-monitoring: "true"
  name: nvidia-network-operator
