---
# yaml-language-server: $schema=/home/tyscott@rich.ciscolabs.com/scotttyso/intersight-tools/schema/cisco-ai-pods.json --- IGNORE ---
# =========================================================
#   Policies -> LAN Connectivity - Variables
# =========================================================
intersight:
  configure:
    common:
      policies:
        bios:
          - bios_template: MLPerf-Inference-C885A-M8-AMD
            name: MLPerf-Inference-C885A-M8-AMD
            ipv4http: disabled
            ipv4pxe: disabled
            ipv6http: disabled
            ipv6pxe: disabled
        ntp:
          - name: C885A
            ntp_servers:
              - 0.pool.ntp.org
              - 1.pool.ntp.org
            timezone: America/New_York
        ipmi_over_lan:
          - name: C885A
            privilege: admin
        local_user:
          - name: C885A
            users:
              - password: 1
                role: admin
                username: root
        ssh:
          - name: C885A
            ssh_port: 22
        power:
          - name: C885A
            power_restore: LastState
            target_platform: Standalone
      profiles:
        server:
          - action: Deploy
            attach_template: false
            bios_policy: MLPerf-Inference-C885A-M8-AMD
            certificate_management_policy: C885A
            ipmi_over_lan_policy: C885A
            local_user_policy: C885A
            ntp_policy: C885A
            power_policy: C885A
            server_family: UCSC885A
            ssh_policy: C885A             # Not Really Necessary unless you want to disable SSH
            target_platform: Standalone
            targets:
              - name: hgxnode5001.ciscolabs.com
                serial_number: WZP22291CF1
                username: root
                password: 1
                server_address: hgxnode5001.ciscolabs.com
              - name: hgxnode5002.ciscolabs.com
                serial_number: WZP22291CF2
                username: root
                password: 1
                server_address: hgxnode5002.ciscolabs.com
shared_services:
  dns_servers:
    - 208.67.222.222
    - 208.67.220.220
  # Option Below if you want to use a proxy server for Device Registration to Intersight, etc.
  # proxy_servers:
  #   https_server: https://proxy.ciscolabs.com:8080
