apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5" # Ensures this is applied AFTER the operator is ready
    deployOVS: 'false'
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec:
  applicationAwareConfig:
    allowApplicationAwareClusterResourceQuota: false
    vmiCalcConfigName: DedicatedVirtualResources
  certConfig:
    ca:
      duration: 48h0m0s
      renewBefore: 24h0m0s
    server:
      duration: 24h0m0s
      renewBefore: 12h0m0s
  deployVmConsoleProxy: false
  featureGates:
    alignCPUs: false
    decentralizedLiveMigration: false
    declarativeHotplugVolumes: false
    deployKubeSecondaryDNS: false
    disableMDevConfiguration: false
    downwardMetrics: false
    enableMultiArchBootImageImport: false
    persistentReservation: false
  higherWorkloadDensity:
    memoryOvercommitPercentage: 100
  liveMigrationConfig:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 150
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  resourceRequirements:
    vmiCPUAllocationRatio: 10
  virtualMachineOptions:
    disableFreePageReporting: false
    disableSerialConsoleLog: true
  workloadUpdateStrategy:
    batchEvictionInterval: 1m0s
    batchEvictionSize: 10
    workloadUpdateMethods:
      - LiveMigrate
  workloads: {}
  uninstallStrategy: BlockUninstallIfWorkloadsExist
