---
  ############################
  # Certificates
  ############################
  - name: Settings > Access > Certificates > SSL Certificate | for {{ array_fqdn }}
    purestorage.flasharray.purefa_certs:
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      certificate: "{{ lookup('file', lookup('ansible.builtin.env', 'cert_mgmt_certificate_{{ element.certificate }}')) }}"
      intermediate_cert: "{{ lookup('file', lookup('ansible.builtin.env', 'cert_mgmt_intermediate_certificate_{{ element.intermediate_certificate }}')) | default('') }}"
      key: "{{ lookup('file', lookup('ansible.builtin.env', 'cert_mgmt_private_key_{{ element.private_key }}')) }}"
      passphrase: "{{ lookup('ansible.builtin.env', 'cert_mgmt_passphrase_{{ element.passphrase }}') | default('') }}"
    loop_control:
      loop_var: element
    loop: "{{ security.certificates.array_certificates }}"
    when: security.certificates is defined and security.certificates.array_certificates is defined and array_fqdn in element.array_fqdns

  ############################
  # Directory Service
  ############################
  - name: Settings > Security > Directory Service > Role Mappings Purity Version < 6.6.3 | for {{ array_fqdn }}
    purestorage.flasharray.purefa_dsrole_old:
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      group: "{{ element.group | default(null) }}"
      group_base: "{{ element.group_base | default(null) }}"
      role: "{{ element.role }}"
      state: "{{ element.state | default('present') }}"
    loop_control:
      loop_var: element
    loop: "{{ security.directory_service.role_mappings }}"
    when: security.directory_service is defined and security.directory_service.role_mappings is defined and array_version < '6.6.3'

  - name: Settings > Security > Directory Service > Role Mappings Purity Version 6.6.3+ | for {{ array_fqdn }}
    purestorage.flasharray.purefa_dsrole:
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      group: "{{ element.group | default(null) }}"
      group_base: "{{ element.group_base | default(null) }}"
      role: "{{ element.role }}"
      state: "{{ element.state | default('present') }}"
    loop_control:
      loop_var: element
    loop: "{{ security.directory_service.role_mappings }}"
    when: security.directory_service is defined and security.directory_service.role_mappings is defined and array_version >= '6.6.3'

  - name: Settings > Security > Directory Service > Configuration | for {{ array_fqdn }}
    purestorage.flasharray.purefa_ds:
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      base_dn: "{{ element.base_dn }}"
      bind_password: "{{ lookup('ansible.builtin.env', 'binding_parameters_password_{{ element.bind_password }}') }}" 
      bind_user: "{{ element.bind_user }}"
      dstype: "{{ element.type | default('management') }}"
      enable: "{{ element.enabled | default(true) }}"
      state: "{{ element.state | default('present') }}"
      uri: "{{ element.uri_list }}"
      user_login: "{{ element.user_login_attribute | default('sAMAccountName') }}"
      user_object: "{{ element.user_object_class | default('User') }}"
    loop_control:
      loop_var: element
    loop: "{{ security.directory_service.configuration }}"
    when: security.directory_service is defined and security.directory_service.configuration is defined
