---
  ############################
  # Flash Array - Local Users
  ############################
  - name: Settings > Access > Users and Policies > Users - Delete
    purestorage.flasharray.purefa_user:
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      name: "{{ element.name }}"
      state: absent
    loop_control:
      loop_var: element
    loop: "{{ pure_storage.settings.security.users }}"

  - name: Settings > Access > Users and Policies > Users
    purestorage.flasharray.purefa_user:
      api: "{{ element.api_token | default(false) }}"
      api_token: "{{ api_token }}"
      disable_warnings: true
      fa_url: "{{ array_url }}"
      name: "{{ element.name }}"
      password: "{{ lookup('ansible.builtin.env', 'binding_parameters_password_{{ element.password }}') if element.password > 0 else lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=20) }}"
      public_key: ""
      role: "{{ element.role }}"
      state: "{{ element.state | default('present') }}"
    loop_control:
      loop_var: element
    loop: "{{ pure_storage.settings.security.users }}"
    register: flash_array_users

  ############################
  # User Outputs
  ############################
  - name: Flash Array > User Results - Print
    debug:
      var: flash_array_users.results

  - name: Flash Array > Users - create JSON outputs
    template:
      src: flash_array.json.j2
      dest: flash_array.json
    when: pure_storage.flash_arrays is defined and pure_storage.settings.security.users
