apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: lldpd
  namespace: lldpd
spec:
  selector:
    matchLabels:
      app: lldpd
  template:
    metadata:
      labels:
        app: lldpd
    spec:
      containers:
        - name: lldpd
          args: ["-d"]
          command: ["lldpd"]
          image: ghcr.io/lldpd/lldpd
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["NET_ADMIN", "NET_RAW"]
            privileged: true
          volumeMounts:
            - name: os-release
              mountPath: /etc/os-release
      hostNetwork: true
      serviceAccountName: lldpd
      # tolerations:
      # - key: node-role.kubernetes.io/control-plane
      #   operator: Exists
      #   effect: NoSchedule
      # - key: node-role.kubernetes.io/master
      #   operator: Exists
      #   effect: NoSchedule
      volumes:
      - name: os-release
        hostPath:
          path: /etc/os-release
