{{- if not (eq .Values.trainer "Removed") }}
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-jobset-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: JobSetOperator.v1.operator.openshift.io
    argocd.argoproj.io/sync-wave: "2"
  name: openshift-jobset-operator-group
  namespace: openshift-jobset-operator
spec:
  targetNamespaces: 
    - openshift-jobset-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/kueue-operator.openshift-kueue-operator: ""
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: jobset-operator
  namespace: openshift-jobset-operator
spec:
  channel: stable-v1.0
  installPlanApproval: {{ .Values.installPlanApproval | default "Manual" }}
  name: job-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jobset-operator.v1.0.0
{{- end }}