apiVersion: v1
kind: Namespace
metadata:
  name: openshift-lws-operator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: LeaderWorkerSetOperator.v1.operator.openshift.io
    argocd.argoproj.io/sync-wave: "2"
  name: openshift-lws-operator-group
  namespace: openshift-lws-operator
spec:
  targetNamespaces:
    - openshift-lws-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/leader-worker-set.openshift-lws-operator: ""
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: leader-worker-set
  namespace: openshift-lws-operator
spec:
  channel: stable-v1.0
  installPlanApproval: {{ ((.Values.global) | default dict).installPlanApproval | default "Manual" }}
  name: leader-worker-set
  source: redhat-operators
  sourceNamespace: openshift-marketplace
