---
- name: Create Portworx Secret pure.json file
  connection: local
  gather_facts: false
  hosts: localhost
  vars:
    everpure_vars_dir: "{{ playbook_dir }}/script_vars"

  pre_tasks:
    - name: Load variables from script folder
      ansible.builtin.include_vars:
        dir: "{{ everpure_vars_dir }}"
        extensions:
          - yaml
          - yml

    - name: Validate portworx configuration exists
      ansible.builtin.assert:
        that:
          - everpure is defined
          - everpure.portworx is defined
          - (everpure.flash_arrays is defined) or (everpure.flash_blades is defined)
        fail_msg: "everpure.portworx or array inventory is missing from script_vars."

  tasks:
    - name: Everpure | Flash Array | Portworx
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/portworx/flash_array.yaml"
      vars:
        flash_arrays: "{{ everpure.flash_arrays }}"
      when: everpure.flash_arrays is defined

    - name: Everpure | Flash Blade | Portworx
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/tasks/portworx/flash_blade.yaml"
      vars:
        flash_blades: "{{ everpure.flash_blades }}"
      when: everpure.flash_blades is defined

    - name: Create the pure.json secret from the result outputs
      ansible.builtin.copy:
        content: "{{ lookup('template', 'pure.json.j2') | to_nice_json }}"
        dest: "{{ playbook_dir }}/pure.json"
        mode: "0600"
