- name: Download and extract tarball in one step
  ansible.builtin.unarchive:
    src: "{{ openshift.operators.cilium.download_url }}"
    dest: "{{ assisted_installer_directory }}/manifests"
    remote_src: yes

- name: Replace the default Cilium Config from Template
  ansible.builtin.copy:
    content: "{{ lookup('template', 'cilium-config.yaml.j2') }}"
    dest: "{{ assisted_installer_directory }}/manifests/ciliumconfig.yaml"

- name: Import the Cilium Subscription YAML file
  ansible.builtin.set_fact:
    subscription_yaml: "{{ lookup('file', assisted_installer_directory + '/manifests/subscription.yaml') | from_yaml }}"
  when: openshift.operators.cilium.enable_kube_proxy_replacement | default(false)

- name: Replace the default Subscription Config from Template
  ansible.builtin.copy:
    content: "{{ lookup('template', 'cilium-subscription.yaml.j2') }}"
    dest: "{{ assisted_installer_directory }}/manifests/subscription.yaml"
  when: openshift.operators.cilium.enable_kube_proxy_replacement | default(false)

- name: Create the Network Manifest file when Kube Proxy Replacement is enabled
  ansible.builtin.copy:
    content: "{{ lookup('template', 'cilium-network.yaml.j2') }}"
    dest: "{{ assisted_installer_directory }}/manifests/cluster-network-02-config-local.yaml"
  when: openshift.operators.cilium.enable_kube_proxy_replacement | default(false)
