---
- name: Set Fact for Proxy Password if provided
  ansible.builtin.set_fact:
    proxy_password: "{{ lookup('ansible.builtin.env', 'proxy_password_' + openshift_install.proxy.password) }}"
  when: openshift_install.proxy.password is defined

- name: Create Proxy Manifest
  ansible.builtin.copy:
    content: "{{ lookup('template', 'iserver-proxy.json.j2') | to_nice_json(indent=4) }}"
    dest: "{{ assisted_installer_directory }}/proxy.json"
    mode: '0644'
