---
- name: Configure OATH LDAP Authentication for OpenShift
  connection: local
  hosts: localhost
  gather_facts: no
  vars:
    validate_certificates: false

  tasks:
    - name: Load variables from script folder
      ansible.builtin.include_vars:
        dir: "{{ playbook_dir }}/script_vars"

    - name: Log in to OpenShift (requires oc binary on host)
      ansible.builtin.command:
        cmd: oc login --token={{ lookup('ansible.builtin.env', 'openshift_token_id') }} --server={{ lookup('ansible.builtin.env', 'openshift_api_url') }}
      register: login_result
      no_log: true
      changed_when: false
    
    - name: Create Otel Operator namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: otel
        state: present
        validate_certs: "{{ validate_certificates }}"

    - name: Ensure the Etcd Folders exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ item }}"
        state: directory
      loop:
        - client
        - signer

    - name: Download Etcd Metric Certificates
      ansible.builtin.shell:
        cmd: "oc extract secret/etcd-metric-{{ item }} -n openshift-etcd --to={{ playbook_dir }}/{{ item }}"
      loop:
        - client
        - signer
      when: splunk_observability.otel_collector.metrics_collection.etcd_metrics

    - name: Create Etcd Secrets for Splunk Observability
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: splunk-monitoring-etcd-metrics-{{ item }}
            namespace: otel
          data:
            tls.crt: "{{ lookup('file', playbook_dir + '/' + item + '/tls.crt') | b64encode }}"
            tls.key: "{{ lookup('file', playbook_dir + '/' + item + '/tls.key') | b64encode }}"
        validate_certs: "{{ validate_certificates }}"
      loop:
        - client
        - signer
      when: splunk_observability.otel_collector.metrics_collection.etcd_metrics


    - name: Add Splunk Otel Collector Chart Repository
      kubernetes.core.helm_repository:
        name: splunk-otel-collector-chart
        repo_url: https://signalfx.github.io/splunk-otel-collector-chart
        state: present
        validate_certs: "{{ validate_certificates }}"

    - name: Create Splunk Otel Collector values.yaml from template
      ansible.builtin.template:
        src: otel-values.yaml.j2
        dest: "{{ playbook_dir }}/values.yaml"

    - name: Deploy Splunk Otel Collector Chart
      kubernetes.core.helm:
        chart_ref: splunk-otel-collector-chart/splunk-otel-collector
        name: splunk-otel-collector
        release_namespace: otel
        state: present
        validate_certs: "{{ validate_certificates }}"
        disable_hook: True
        force: True
        replace: True
        update_repo_cache: True
        wait: True
        release_values:
          clusterName: "{{ splunk_observability.cluster.name }}"
          environment: "{{ splunk_observability.cluster.environment }}"
          splunkObservability:
            acccessToken: "{{ lookup('ansible.builtin.env', 'splunk_observability_token') }}"
            realm: "{{ splunk_realm }}"
          splunkPlatform:
            endpoint: "{{ splunk_observability.splunk_platform.endpoint }}"
            index: "{{ splunk_observability.splunk_platform.index }}"
            token: "{{ lookup('ansible.builtin.env', 'splunk_platform_token') }}"
        values_files:
          - "{{ playbook_dir }}/values.yaml"

    - name: Delete Generated Files / Directories
      ansible.builtin.file:
        path: "{{ playbook_dir }}/{{ item }}"
        state: absent
      loop:
        - client
        - signer
        - values.yaml

    - name: Create Intersight Otel Operator namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: intersight-otel
        state: present
        validate_certs: "{{ validate_certificates }}"
      when: splunk_observability.intersight is defined

    - name: Create Intersight Secret for Splunk Observability
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: intersight-api-credentials
            namespace: intersight-otel
          data:
            intersight-key-id: "{{ lookup('file', splunk_observability.intersight.key_id_path) | b64encode }}"
            intersight-key: "{{ lookup('file', splunk_observability.intersight.key_path) | b64encode }}"
        validate_certs: "{{ validate_certificates }}"
      when: splunk_observability.intersight is defined

    - name: Configure Intersight Otel
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', item) | from_yaml }}"
        validate_certs: "{{ validate_certificates }}"
      loop:
        - intersight-config-map.yaml.j2
        - intersight-deployment.yaml.j2
      when: splunk_observability.intersight is defined

    - name: Create Nexus Exporter namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: cisco-exporter
        state: present
        validate_certs: "{{ validate_certificates }}"
      when: splunk_observability.nexus is defined

    # - name: Create Nexus Exporter Secret for Device Password
    #   kubernetes.core.k8s:
    #     state: present
    #     definition:
    #       apiVersion: v1
    #       kind: Secret
    #       metadata:
    #         name: nexus-device-credentials
    #         namespace: cisco-exporter
    #       data:
    #         username: "{{ splunk_observability.nexus.username | b64encode }}"
    #         password: "{{ lookup('ansible.builtin.env', 'nexus_device_password') | b64encode }}"
    #     validate_certs: "{{ validate_certificates }}"
    #   when: splunk_observability.nexus is defined

    - name: Set Nexus Device Password Fact
      ansible.builtin.set_fact:
        nexus_device_password: "{{ lookup('ansible.builtin.env', 'nexus_device_password') }}"
      when: splunk_observability.nexus is defined

    - name: Configure Nexus Exporter
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', item) | from_yaml }}"
        validate_certs: "{{ validate_certificates }}"
      loop:
        - nexus-config-map.yaml.j2
        - nexus-deployment.yaml.j2
        - nexus-service.yaml.j2
      when: splunk_observability.nexus is defined

