---
- name: Include Intersight organization configuration
  ansible.builtin.import_tasks: organizations.yml
  tags: [organizations]

- name: Include Intersight pool configuration
  ansible.builtin.import_tasks: pools.yml
  tags: [pools]

- name: Include Intersight policy configuration
  ansible.builtin.import_tasks: policies.yml
  tags: [policies]

- name: Include Intersight profile configuration
  ansible.builtin.import_tasks: profiles.yml
  tags: [profiles]
